### ISSUE TITLE
error in running demo file

### ISSUE THREAD

**Issue by Yoshio-yoshioka** [ncod3/vprimer#2]
Hello,

I successfully installed vprimer in a virtual environment (I named it env_vprimer) following the manual.
but I encountered error messages while executing the demo scripts.

Below is the message I encountered after running the first demo script file.
It ends with "NameError: name '_log' is not defined".
One of the created files in directory "ref", TDr96_F1_v2_PC_ch01_ch02.fasta.gz_BGZIP.gz, was zero bites, seemingly not correctly generated.

> (env_vprimer) yoshio@iMac test_vprimer % sh ./010.show_samples.sh
> prelog: vprimer.conf not exist dir /Users/yoshio/Analysis/vprimer/test_vprimer/out_vprimer.
> prelog: vprimer.conf not exist dir /Users/yoshio/Analysis/vprimer/test_vprimer/out_vprimer/logs.
> prelog: vprimer.conf not exist dir /Users/yoshio/Analysis/vprimer/test_vprimer/out_vprimer/bak.
> 2023-10-21 18:59:50,323 INFO logging_config open_log 77: logging start vprimer.conf
> 2023-10-21 18:59:50,323 INFO utils open_log 33: logging start vprimer.utils
> 2023-10-21 18:59:50,324 INFO logging_config open_log 77: logging start vprimer.param
> 2023-10-21 18:59:50,324 INFO logging_config open_log 77: logging start vprimer.conf_ref_fasta
> 2023-10-21 18:59:50,324 INFO logging_config open_log 77: logging start vprimer.conf_vcf_file
> 2023-10-21 18:59:50,324 INFO logging_config open_log 77: logging start vprimer.conf_distin
> 2023-10-21 18:59:50,325 INFO logging_config open_log 77: logging start vprimer.conf_p3_params
> 2023-10-21 18:59:50,325 INFO logging_config open_log 77: logging start vprimer.conf_enzyme
> 2023-10-21 18:59:50,325 INFO logging_config open_log 77: logging start vprimer.conf_bed_file
> 2023-10-21 18:59:50,325 INFO logging_config open_log 77: logging start vprimer.conf_curr_setting
> 2023-10-21 18:59:50,326 INFO logging_config open_log 77: logging start vprimer.conf_amplicon
> 2023-10-21 18:59:50,326 INFO logging_config open_log 77: logging start vprimer.outlist
> 2023-10-21 18:59:50,326 INFO logging_config open_log 77: logging start vprimer.main
> 2023-10-21 18:59:50,327 INFO logging_config open_log 77: logging start vprimer.variant
> 2023-10-21 18:59:50,327 INFO logging_config open_log 77: logging start vprimer.marker
> 2023-10-21 18:59:50,328 INFO logging_config open_log 77: logging start vprimer.primer
> 2023-10-21 18:59:50,735 INFO logging_config open_log 77: logging start vprimer.formtxt
> 2023-10-21 18:59:50,735 INFO logging_config open_log 77: logging start vprimer.chkhdimer
> 2023-10-21 18:59:50,735 INFO main main 29: vprimer started at 2023_1021_1859_50
> 2023-10-21 18:59:50,735 INFO conf choice_variables 407: thread=2
> 2023-10-21 18:59:50,736 INFO conf thread_adjusting 1014: Parallel execution mode is turned off when the number of threads used is less than or equal to 5. now=2.
> 2023-10-21 18:59:50,736 INFO conf print_param_ini 1241: 
> ======== param.p ====================
> 2023-10-21 18:59:50,736 INFO conf print_param_ini 1242: self.param.p=
> 
> {'a_sample': None,
>  'amplicon_param': None,
>  'auto_group': None,
>  'b_sample': None,
>  'bam_table': None,
>  'bed_thal': None,
>  'enzyme': None,
>  'enzyme_file': None,
>  'homo_only': False,
>  'indel_size': None,
>  'ini_file': None,
>  'min_max_depth': None,
>  'out_dir': None,
>  'p3_amplicon': None,
>  'p3_normal': None,
>  'pick_mode': None,
>  'product_size': None,
>  'progress': None,
>  'ref': 'data_vprimer/TDr96_F1_v2_PC_ch01_ch02.fasta.gz',
>  'show_fasta': False,
>  'show_samples': True,
>  'snp_filter': None,
>  'stop': None,
>  'target': None,
>  'thread': None,
>  'vcf': 'data_vprimer/MP2_6_TDr96_F1.vcf.gz'}
> 
> 2023-10-21 18:59:50,736 INFO conf print_param_ini 1244: 
> ======== ini.ini['vprimer'] =========
> 2023-10-21 18:59:50,736 INFO conf print_param_ini 1251: ini_file not specified.
> 2023-10-21 18:59:50,736 INFO conf print_param_ini 1252: 
> =====================================
> 
> 2023-10-21 18:59:50,753 INFO conf setup_variables 898: setup_variables, START.
> 2023-10-21 18:59:50,753 INFO conf_ref_fasta prepare_ref 37: prepare_ref start.
> 2023-10-21 18:59:50,753 INFO utils is_need_update 1169: not exist dist_pathlib /Users/yoshio/Analysis/vprimer/test_vprimer/refs/slink_TDr96_F1_v2_PC_ch01_ch02.fasta.gz
> 2023-10-21 18:59:50,754 INFO utils is_need_update 1195: need_update True.
> 2023-10-21 18:59:50,754 INFO utils refs_file_slink_backup_and_copy 428: NEED to update between /Users/yoshio/Analysis/vprimer/test_vprimer/data_vprimer/TDr96_F1_v2_PC_ch01_ch02.fasta.gz and /Users/yoshio/Analysis/vprimer/test_vprimer/refs/slink_TDr96_F1_v2_PC_ch01_ch02.fasta.gz.
> 2023-10-21 18:59:50,754 INFO utils try_exec 248: do ln -s /Users/yoshio/Analysis/vprimer/test_vprimer/data_vprimer/TDr96_F1_v2_PC_ch01_ch02.fasta.gz /Users/yoshio/Analysis/vprimer/test_vprimer/refs/slink_TDr96_F1_v2_PC_ch01_ch02.fasta.gz
> 2023-10-21 18:59:50,764 INFO utils is_need_update 1169: not exist dist_pathlib /Users/yoshio/Analysis/vprimer/test_vprimer/refs/TDr96_F1_v2_PC_ch01_ch02.fasta.gz_BGZIP.gz
> 2023-10-21 18:59:50,765 INFO utils is_need_update 1195: need_update True.
> 2023-10-21 18:59:50,765 INFO conf_ref_fasta update_bgzip_fasta 96: ext=[.gz], self.user_ref_path=/Users/yoshio/Analysis/vprimer/test_vprimer/data_vprimer/TDr96_F1_v2_PC_ch01_ch02.fasta.gz.
> Traceback (most recent call last):
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/utils.py", line 250, in try_exec
>     sbp.run(cmd,
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/subprocess.py", line 516, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'bgzip -cd -@ 1 /Users/yoshio/Analysis/vprimer/test_vprimer/data_vprimer/TDr96_F1_v2_PC_ch01_ch02.fasta.gz | bgzip -@ 1 > /Users/yoshio/Analysis/vprimer/test_vprimer/refs/TDr96_F1_v2_PC_ch01_ch02.fasta.gz_BGZIP.gz' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/bin/vprimer", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/main.py", line 33, in main
>     vpr.run()
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/main.py", line 74, in run
>     self.prepare()
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/main.py", line 58, in prepare
>     glv.conf.setup_variables()
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/conf.py", line 909, in setup_variables
>     self.prepare_refs_dir()
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/conf.py", line 821, in prepare_refs_dir
>     self.prepare_ref(
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/conf_ref_fasta.py", line 71, in prepare_ref
>     self.update_bgzip_fasta(src_path, bgzip_path)
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/conf_ref_fasta.py", line 115, in update_bgzip_fasta
>     utl.try_exec(cmd1)
>   File "/usr/local/Caskroom/miniconda/base/envs/env_vprimer/lib/python3.8/site-packages/vprimer/utils.py", line 258, in try_exec
>     if _log == True:
> NameError: name '_log' is not defined

And if I continue to the second demo file, lines of messages ending with :

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/yoshio/Analysis/vprimer/test_vprimer/refs/TDr96_F1_v2_PC_ch01_ch02.fasta.gz_BGZIP.gz.pickle'

appear, and the process hangs up. 

My computer is macOS Ventura  13.3.
I would greatly appreciate any advice that you can offer me.

Thank you,

**Comment by ncod3** [comment]
Thank you very much for installing V-primer and trying out the program.

I am currently preparing to reproduce the error. I will report here as soon as I know the situation, so please wait for a moment.
